spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#多个active 用逗号隔开
book:
  name: 高性能linux服务器构建
  author: 高俊峰
  isbn: ${random.uuid}
  description: ${book.name}, 很不错
logging:
  level:
    root: info
    com.jiuxin: debug
  file: logs/my.log

#application-{pro}.yml {}内为自定义名

#SSHCLIENT
sshClient:
  hostip: 119.3.44.155
  username: root
  password: jiuxin123

mqtt:
  hostip: tcp://119.3.46.253:1883
  username: admin
  password: public