server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/springbootdev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Jiuxin123@db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  resources:
#    static-locations: ["/templates/","/static/"]

logging:
  level: info
  file: logs/debug.log
