server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level: info
  file: logs/debug.log
